### PR TITLE
Update 404.html

### PR DESCRIPTION
**Pull request by puntillol59**
Add stuff for support, if the webpage is down.

### CODE REVIEW

**Comment by puntillol59** [comment]
This pull isn't needed.

**Comment by nmcain** [comment]
Perhaps prompt the user to file an issue here?

**Comment by puntillol59** [comment]
Sure, lemma reopen.

**Comment by puntillol59** [comment]
Ah, already reopened

**Comment by puntillol59** [comment]
Added issues page.

**Comment by Looskie** [comment]
Already implemented

**Pull request closed without merging**
